# Generated by Django 5.0.7 on 2024-08-30 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercializadoras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nic', models.CharField(error_messages={'unique': 'Ya existe una comercializadora con ese NIC. Por favor, elige uno diferente.'}, max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarifa', models.CharField(max_length=20)),
                ('inicio', models.CharField(max_length=20)),
                ('fin', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UVT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anho', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(db_index=True, max_length=50, unique=True)),
                ('usuario', models.CharField(default=True, max_length=100, null=True)),
                ('categoria', models.CharField(default='', max_length=255)),
                ('direccion', models.CharField(default=True, max_length=255, null=True)),
                ('email', models.CharField(default=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('comercializadora', models.ManyToManyField(related_name='comercializadora', to='api.comercializadoras')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nic', models.CharField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('comercializadora', models.ManyToManyField(blank=True, related_name='contratos', to='api.comercializadoras')),
                ('nit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='nit')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anho', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('nic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contrato', to_field='nic')),
            ],
        ),
    ]
